### PR TITLE
Add Create Update Delete functionalities

### PR DESCRIPTION
**Pull request by acolombo1**
- Remove all hardcoded items from the tasks array.
- Create a new JavaScript file for the new functionality.
- Implement a function for adding a new task (add a new element to the array).
- Implement a function for deleting a task (remove an element from the array).
- Implement a function for editing task descriptions.
- New tasks have the property completed set to false and the property index set to the value of the new array length.
- Deleting a task updates all remaining items' indexes.
- Changes saved in local storage.

### CODE REVIEW

**Review by topeogunleye — CHANGES_REQUESTED** [review]
> # Changes Required 
> ### Hi @acolombo1,
> Nice job, you are almost there.
> 
> 
> 
> ## (Highlights) Good Points: 
> * No linter errors. :heavy_check_mark:
> * Followed Github flow :heavy_check_mark:
>
> ## (Changes Required) Aspects to improve: 
>- [x] Great job adding the functionality of adding a task, marking a task as completed, and clearing all completed tasks. Please kindly make sure your functionality to delete a task (remove an element from the array) is implemented correctly because there is currently no delete icon on the webpage to add an event listener for removing an item from the task list array.

Edit: **Note to next reviewer**:. Please Approve. I think the fault was from my browser. 

https://user-images.githubusercontent.com/52934128/165882771-d6e23996-afe7-40d2-ae6d-06e921615787.mp4


>- [x] From now on,please kindly make use of imperative mood in the subject line for your commit messages.
:x: Wrong
Screenshot from 2022-04-29 04-40-04
> ### Good Commit Messages:
>- [x]  Add fix for dark mode toggle state
>- [x] Update README file.
>- [x] Add styles to h1.
>
> ## [Optional] suggestions:
> * Nothing to mention.
> 
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> **Cheers and Happy coding! :clap::clap::clap:**
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear
> Please, remember to tag @topeogunleye in your question so I can receive the notification.
>
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by acolombo1** [comment]
@topeogunleye: Hi, do you use any tool for running the app from the Github directory? In the video you show me, the images are not loaded for some reason. You can view the live demo: https://acolombo1.github.io/todolist/dist/. I suppose that if you download the dist directory to your local computer it should also run correctly.
Please tell me if this might be an issue on your side, or if you know what can I do to resolve the problem. Both the return icon and the trash can icon are not shown in your video, but they must be still clickable because I can see the pointer briefly.

The list items can also be deleted by entering a zero-length description.

I will see if this could have anything to do with my Webpack configuration.

**Comment by topeogunleye** [comment]
> @topeogunleye: Hi, do you use any tool for running the app from the Github directory? In the video you show me, the images are not loaded for some reason. You can view the live demo: https://acolombo1.github.io/todolist/dist/. I suppose that if you download the dist directory to your local computer it should also run correctly. Please tell me if this might be an issue on your side, or if you know what can I do to resolve the problem. Both the return icon and the trash can icon are not shown in your video, but they must be still clickable because I can see the pointer briefly.
> 
> The list items can also be deleted by entering a zero-length description.
> 
> I will see if this could have anything to do with my Webpack configuration.

@acolombo1, I used Gitpod, then I ran it locally with Webstorm. It must have been from my browser. I have left a note to the next reviewer, Kindly submit again and you'll get approved. If you want to. You also can wait while I try to get help to change my requested changes to approval. I sincerely apologize for the delay in approval

```
Hello @acolombo1!

I've just realized that the problem was from my browser.
I am sorry to have not approved your project. I haven't done that on purpose :blush:
```

**Comment by enniopo** [comment]
Hi @acolombo1,

I have marked the project as completed now. If you refresh your dashboard you should be able to see it. 
Congratulations 🎉

**Pull request merged**
